table tb_midia
	lineageTag: 9001ba58-48e9-4528-af6c-451866bf6a74
	sourceLineageTag: [dbo].[tb_midia]

	measure abertas_andamento = CALCULATE([Contagem], FILTER(tb_midia, tb_midia[Status vaga] = "ABERTA" ||tb_midia[Status vaga] = "EM ANDAMENTO" ))
		lineageTag: 02a09cc0-5e77-4cdf-93ad-5de02e321f87

		changedProperty = Name

	measure Contagem = DISTINCTCOUNT(tb_midia[Codigo vaga])
		formatString: 0
		lineageTag: 127a11b8-9aae-47ad-94e6-b7889a35ecd8

		changedProperty = Name

	measure gap = DIVIDE([abertas_andamento],[Contagem],0)
		formatString: 0%;-0%;0%
		lineageTag: 8106c21b-1019-45f3-918e-704dd0730655

		changedProperty = Name

		changedProperty = FormatString

	column 'Codigo vaga'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 62441a14-9fa1-4cd9-b7cb-7d4b7572f0f7
		sourceLineageTag: Codigo vaga
		summarizeBy: none
		sourceColumn: Codigo vaga

		annotation SummarizationSetBy = Automatic

	column Localidade
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 9a98d895-e49a-460a-a7ca-dbf3f23e4dd8
		sourceLineageTag: Localidade
		summarizeBy: none
		sourceColumn: Localidade

		annotation SummarizationSetBy = Automatic

	column 'Data abertura'
		dataType: dateTime
		formatString: General Date
		sourceProviderType: date
		lineageTag: c57d98bc-abbf-4bb1-baba-825ce00a05ad
		sourceLineageTag: Data abertura
		summarizeBy: none
		sourceColumn: Data abertura

		annotation SummarizationSetBy = Automatic

	column 'Data admissão'
		dataType: dateTime
		formatString: General Date
		sourceProviderType: date
		lineageTag: b2fbbeab-fff7-4021-bdaa-f1e7f6a16929
		sourceLineageTag: Data admissão
		summarizeBy: none
		sourceColumn: Data admissão

		annotation SummarizationSetBy = Automatic

	column 'Status processo'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 9e776dc9-199f-4135-bd97-3d10c1097896
		sourceLineageTag: Status processo
		summarizeBy: none
		sourceColumn: Status processo

		annotation SummarizationSetBy = Automatic

	column Colaborador
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: ed423a80-996e-4637-a231-438a7d1cdbd8
		sourceLineageTag: Colaborador
		summarizeBy: none
		sourceColumn: Colaborador

		annotation SummarizationSetBy = Automatic

	column 'Status vaga'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: f645b994-6c34-46fb-8699-64dd4f521a76
		sourceLineageTag: Status vaga
		summarizeBy: none
		sourceColumn: Status vaga

		annotation SummarizationSetBy = Automatic

	column Função
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: c3829ce8-c909-412b-a328-200967d7d2d9
		sourceLineageTag: Função
		summarizeBy: none
		sourceColumn: Função

		annotation SummarizationSetBy = Automatic

	column 'Tipo de recrutamento'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: ca53c92f-842c-4973-bc73-531fec070e04
		sourceLineageTag: Tipo de recrutamento
		summarizeBy: none
		sourceColumn: Tipo de recrutamento

		annotation SummarizationSetBy = Automatic

	column Salário
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 333edec9-8aca-484d-89cd-727e028f5740
		sourceLineageTag: Salário
		summarizeBy: none
		sourceColumn: Salário

		annotation SummarizationSetBy = Automatic

	column midia
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 595fe87f-919b-43e2-9c19-83ac3333a741
		sourceLineageTag: midia
		summarizeBy: none
		sourceColumn: midia

		annotation SummarizationSetBy = Automatic

	column legado
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 1144793e-f66c-43dc-8c51-ead2bafc1770
		sourceLineageTag: legado
		summarizeBy: none
		sourceColumn: legado

		annotation SummarizationSetBy = Automatic

	column 'Colaborador Substituído'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 9015abaa-a823-456a-93fa-09ae67d821a7
		sourceLineageTag: Colaborador Substituído
		summarizeBy: none
		sourceColumn: Colaborador Substituído

		annotation SummarizationSetBy = Automatic

	column Recrutador_a_Id
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 072d5441-2f0a-4aac-8bea-fc51e76088de
		sourceLineageTag: Recrutador_a_Id
		summarizeBy: none
		sourceColumn: Recrutador_a_Id

		annotation SummarizationSetBy = Automatic

	column Recrutador_a_StringId
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: a8f5e030-6dff-4378-bafc-39f3d502048b
		sourceLineageTag: Recrutador_a_StringId
		summarizeBy: none
		sourceColumn: Recrutador_a_StringId

		annotation SummarizationSetBy = Automatic

	column Gestor
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 280c2023-10f8-4cb7-bf6e-81224a6cd7c1
		sourceLineageTag: Gestor
		summarizeBy: none
		sourceColumn: Gestor

		annotation SummarizationSetBy = Automatic

	column observacoes
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 58cdc786-1c05-4e21-a349-cfaef349dabf
		sourceLineageTag: observacoes
		summarizeBy: none
		sourceColumn: observacoes

		annotation SummarizationSetBy = Automatic

	column Status_ID
		dataType: string
		sourceProviderType: int
		lineageTag: 297bc50a-626b-42ee-b8b0-2c50f8fbccba
		sourceLineageTag: Status_ID
		summarizeBy: none
		sourceColumn: Status_ID

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	partition tb_midia = entity
		mode: directLake
		source
			entityName: tb_midia
			schemaName: dbo
			expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table

