CREATE TABLE [dbo].[tb_colaboradores_staging] (

	[ADMISSAO] datetime2(6) NULL, 
	[CARGO] varchar(8000) NULL, 
	[CARGO_ANTERIOR] varchar(8000) NULL, 
	[CAUSA_RESCISÃO] varchar(8000) NULL, 
	[CEP] varchar(8000) NULL, 
	[CHAVE] varchar(8000) NULL, 
	[CIDADE_UF] varchar(8000) NULL, 
	[CNPJ] varchar(8000) NULL, 
	[COD_CCUSTO] varchar(8000) NULL, 
	[COD_EMPRESA] varchar(8000) NULL, 
	[CPF] varchar(8000) NULL, 
	[CPF_GESTOR] varchar(8000) NULL, 
	[DEMISSAO] datetime2(6) NULL, 
	[DESCRICAO_CCUSTO] varchar(8000) NULL, 
	[DIRETORIA] varchar(8000) NULL, 
	[DIRETORIA_N2] varchar(8000) NULL, 
	[DT_INICIO_SITUACAO] datetime2(6) NULL, 
	[EMAIL] varchar(8000) NULL, 
	[EMPRESA] varchar(8000) NULL, 
	[EMPRESA_ANTERIOR] varchar(8000) NULL, 
	[ENDEREÇO_COMPLETO] varchar(8000) NULL, 
	[ESTADO_SHOPPING] varchar(8000) NULL, 
	[FAIXA_GRADE] float NULL, 
	[FAIXA_GRADE_INDEX] int NULL, 
	[FILTRO_TRANSFERÊNCIA] int NULL, 
	[GESTOR] varchar(8000) NULL, 
	[GRADE] varchar(8000) NULL, 
	[GRAU_DE_INSTRUCAO] varchar(8000) NULL, 
	[GRAU_DE_INSTRUÇÃO] varchar(8000) NULL, 
	[LEGADO] varchar(8000) NULL, 
	[LEGADO_Ajustado] varchar(8000) NULL, 
	[Link_imagem] varchar(8000) NULL, 
	[MATRICULA] varchar(8000) NULL, 
	[MUNICIPIO] varchar(8000) NULL, 
	[NACIONALIDADE] varchar(8000) NULL, 
	[NASCIMENTO] datetime2(6) NULL, 
	[NIVEIS_HIERARQUIA] int NULL, 
	[NIVEL_1] varchar(8000) NULL, 
	[NIVEL_2] varchar(8000) NULL, 
	[NIVEL_3] varchar(8000) NULL, 
	[NIVEL_4] varchar(8000) NULL, 
	[NIVEL_5] varchar(8000) NULL, 
	[NIVEL_6] varchar(8000) NULL, 
	[NIVEL_7] varchar(8000) NULL, 
	[NOME] varchar(8000) NULL, 
	[ONBOARDING_REGRA] bigint NULL, 
	[PATH_HIERARQUIA] varchar(8000) NULL, 
	[PCD] varchar(8000) NULL, 
	[PORTFÓLIO] varchar(8000) NULL, 
	[RAÇA] varchar(8000) NULL, 
	[REGIAO_SHOPPING] varchar(8000) NULL, 
	[REGIME] varchar(8000) NULL, 
	[SALARIO] float NULL, 
	[SALARIO_100%] float NULL, 
	[SALARIO_ANTERIOR] float NULL, 
	[SEXO] varchar(8000) NULL, 
	[SHOPPING] varchar(8000) NULL, 
	[SITUAÇÃO] varchar(8000) NULL, 
	[UF] varchar(8000) NULL, 
	[UF_NOME] varchar(8000) NULL, 
	[UF_REGIAO] varchar(8000) NULL, 
	[UNIDADE] varchar(8000) NULL, 
	[ÁREA_SHOPPING] varchar(8000) NULL, 
	[É_HELLOO] varchar(8000) NULL, 
	[É_SHOPPING_ADM] varchar(8000) NULL, 
	[Você_já_se_sentiu_desconfortável_em_algum_lugar_por_causa_da_sua_cor?] varchar(8000) NULL, 
	[Você_já_ouviu_piadas_por_conta_da_cor_da_sua_pele_ou_do_seu_tipo_de_cabelo?] varchar(8000) NULL, 
	[Você_já_desejou_ter_outra_cor_de_pele?] varchar(8000) NULL, 
	[Com_qual_cor_ou_raça_você_se_identifica?] varchar(8000) NULL, 
	[GRUPO_CARGO] varchar(22) NOT NULL, 
	[GRAU_ESCOLARIDADE] varchar(18) NOT NULL, 
	[LIDERANÇA] varchar(11) NOT NULL, 
	[LIDERANÇA_MOVER] varchar(11) NOT NULL, 
	[CAMPO] varchar(14) NOT NULL, 
	[REGRA_ATIVOS_TURNOVER] int NOT NULL, 
	[REGRA_DEMITIDOS_TURNOVER] int NOT NULL, 
	[MOTIVO_TURNOVER] varchar(14) NOT NULL, 
	[INDICE_GRUPO_CARGO] int NOT NULL, 
	[INDICE_GRAU_ESCOLARIDADE] int NOT NULL, 
	[RAÇA_AUTODECLARADA] varchar(8000) NULL
);