CREATE TABLE [dbo].[tb_vagas_gupy] (

	[Requisição] varchar(8000) NULL, 
	[Status_da_Vaga] varchar(8000) NULL, 
	[Shopping] varchar(8000) NULL, 
	[Gerente_da_vaga] varchar(8000) NULL, 
	[Email_Gerente] varchar(8000) NULL, 
	[Cargo] varchar(8000) NULL, 
	[Tipo_de_Publicação] varchar(8000) NULL, 
	[Página_de_Carreiras] varchar(8000) NULL, 
	[Recrutador_da_vaga] varchar(8000) NULL, 
	[Data_de_Criação] datetime2(6) NULL, 
	[Data_de_Publicação] datetime2(6) NULL, 
	[Data_de_Fechamento] datetime2(6) NULL, 
	[Última_Data_do_Congelamento] datetime2(6) NULL, 
	[Última_Data_de_Descongelamento] datetime2(6) NULL, 
	[Data_de_cancelamento] datetime2(6) NULL, 
	[Objetivo_da_vaga] varchar(8000) NULL, 
	[PCD] varchar(8000) NULL, 
	[Diretoria_Executiva] varchar(8000) NULL, 
	[Tipo_de_recrutamento] varchar(8000) NULL, 
	[Área/Regional] varchar(8000) NULL, 
	[Vaga_PCD] varchar(8000) NULL, 
	[Motivo] varchar(8000) NULL, 
	[Aprendiz_PCD] varchar(8000) NULL, 
	[Dias_abertos] int NULL, 
	[Unidade_negócio] varchar(8000) NULL, 
	[Líder/Não_líder] varchar(8000) NULL, 
	[Ano_publicação_vaga] int NULL, 
	[Mês_publicação_vaga] varchar(25) NOT NULL, 
	[Grupo_recrutador] varchar(18) NOT NULL
);